[package]
name = "rsmalloc"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rsmalloc = {path = "."}

[[example]]
name = "manual"
path = "example/manual.rs"

[dependencies]
libc = "0.2"
lazy_static = "^1.4.0"
chrono = "^0.4.0"



[target.'cfg(windows)'.dependencies.winapi]
version = "^0.3"
features = ["minwinbase","synchapi","winnt","minwindef","psapi","processthreadsapi","basetsd","handleapi"]

[features]
debug_mode = []
