[package]
name = "rsmalloc"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rsmalloc = {path = "."}
extargsparse_worker = "^0.2.2"
extargsparse_codegen = "^0.1.4"


[[example]]
name = "manual"
path = "example/manual.rs"

[[example]]
name = "multi"
path = "example/multi.rs"

[[example]]
name = "extparser"
path = "example/extparser.rs"


[dependencies]
libc = "0.2"
lazy_static = "^1.4.0"
chrono = "^0.4.0"
regex = "1"



[target.'cfg(windows)'.dependencies.winapi]
version = "^0.3"
features = ["minwinbase","synchapi","winnt","minwindef","psapi","processthreadsapi","basetsd","handleapi"]


[features]
debug_mode = []
